"""
VulnZero - Patch Model
Stores AI-generated patches for vulnerabilities
"""

from datetime import datetime
from typing import Optional
from sqlalchemy import (
    Column, String, Integer, Float, DateTime, Text, JSON, Enum,
    ForeignKey, Index, CheckConstraint, Boolean
)
from sqlalchemy.orm import relationship
import enum

from shared.models.base import Base


class PatchType(str, enum.Enum):
    """Patch type enumeration"""
    PACKAGE_UPDATE = "package_update"
    CONFIG_CHANGE = "config_change"
    SCRIPT_EXECUTION = "script_execution"
    WORKAROUND = "workaround"
    MANUAL = "manual"


class PatchStatus(str, enum.Enum):
    """Patch status enumeration"""
    GENERATED = "generated"
    VALIDATED = "validated"
    TESTING = "testing"
    TEST_PASSED = "test_passed"
    TEST_FAILED = "test_failed"
    APPROVED = "approved"
    REJECTED = "rejected"
    DEPLOYED = "deployed"
    FAILED = "failed"
    ROLLED_BACK = "rolled_back"


class Patch(Base):
    """
    Patch Model - Stores AI-generated patches for vulnerabilities.

    This table stores remediation patches generated by the AI patch generator,
    including the patch content, validation results, and test outcomes.
    """

    __tablename__ = "patches"

    # ========================================================================
    # Foreign Keys
    # ========================================================================
    vulnerability_id = Column(
        Integer,
        ForeignKey("vulnerabilities.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Reference to the vulnerability being patched"
    )

    # ========================================================================
    # Patch Information
    # ========================================================================
    patch_type = Column(
        Enum(PatchType),
        nullable=False,
        index=True,
        comment="Type of patch: package_update, config_change, script, etc."
    )

    status = Column(
        Enum(PatchStatus),
        nullable=False,
        default=PatchStatus.GENERATED,
        index=True,
        comment="Current status of the patch"
    )

    title = Column(
        String(500),
        nullable=False,
        comment="Patch title/summary"
    )

    description = Column(
        Text,
        nullable=True,
        comment="Detailed description of what the patch does"
    )

    # ========================================================================
    # Patch Content
    # ========================================================================
    patch_content = Column(
        Text,
        nullable=False,
        comment="Actual patch script/code (bash, Ansible playbook, etc.)"
    )

    patch_language = Column(
        String(50),
        nullable=False,
        default="bash",
        comment="Scripting language: bash, python, ansible, terraform"
    )

    rollback_script = Column(
        Text,
        nullable=True,
        comment="Script to rollback the patch if needed"
    )

    # ========================================================================
    # AI Generation Details
    # ========================================================================
    llm_provider = Column(
        String(50),
        nullable=False,
        comment="LLM provider used: openai, anthropic"
    )

    llm_model = Column(
        String(100),
        nullable=False,
        comment="Specific model used (gpt-4, claude-3-sonnet, etc.)"
    )

    llm_prompt = Column(
        Text,
        nullable=True,
        comment="Prompt sent to LLM for generation"
    )

    llm_response = Column(
        Text,
        nullable=True,
        comment="Raw response from LLM"
    )

    generation_time_seconds = Column(
        Float,
        nullable=True,
        comment="Time taken to generate patch (seconds)"
    )

    # ========================================================================
    # Validation & Safety
    # ========================================================================
    confidence_score = Column(
        Float,
        nullable=False,
        default=0.0,
        index=True,
        comment="Confidence score for patch safety/effectiveness (0-100)"
    )

    validation_passed = Column(
        Boolean,
        nullable=False,
        default=False,
        comment="Whether patch passed syntax/safety validation"
    )

    validation_errors = Column(
        JSON,
        nullable=True,
        comment="List of validation errors, if any"
    )

    safety_checks = Column(
        JSON,
        nullable=True,
        comment="Results of safety checks (no destructive commands, etc.)"
    )

    # ========================================================================
    # Testing Information
    # ========================================================================
    test_status = Column(
        String(50),
        nullable=True,
        index=True,
        comment="Test status from digital twin"
    )

    test_started_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="When testing started"
    )

    test_completed_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="When testing completed"
    )

    test_duration_seconds = Column(
        Float,
        nullable=True,
        comment="Duration of testing (seconds)"
    )

    test_results = Column(
        JSON,
        nullable=True,
        comment="Detailed test results from digital twin"
    )

    test_logs = Column(
        Text,
        nullable=True,
        comment="Test execution logs"
    )

    # ========================================================================
    # Deployment Tracking
    # ========================================================================
    deployment_method = Column(
        String(50),
        nullable=True,
        comment="Deployment method: ansible, ssh, terraform, etc."
    )

    deployment_count = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Number of times this patch has been deployed"
    )

    success_count = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Number of successful deployments"
    )

    failure_count = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Number of failed deployments"
    )

    rollback_count = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Number of times rolled back"
    )

    # ========================================================================
    # Approval & Review
    # ========================================================================
    requires_approval = Column(
        Boolean,
        nullable=False,
        default=False,
        comment="Whether this patch requires manual approval"
    )

    approved_by = Column(
        String(200),
        nullable=True,
        comment="User who approved the patch"
    )

    approved_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="When patch was approved"
    )

    rejected_by = Column(
        String(200),
        nullable=True,
        comment="User who rejected the patch"
    )

    rejected_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="When patch was rejected"
    )

    rejection_reason = Column(
        Text,
        nullable=True,
        comment="Reason for rejection"
    )

    # ========================================================================
    # Metadata
    # ========================================================================
    version = Column(
        Integer,
        nullable=False,
        default=1,
        comment="Patch version (for retries/improvements)"
    )

    is_template = Column(
        Boolean,
        nullable=False,
        default=False,
        comment="Whether this is a reusable template patch"
    )

    template_category = Column(
        String(100),
        nullable=True,
        comment="Template category (for template patches)"
    )

    tags = Column(
        JSON,
        nullable=True,
        comment="Custom tags"
    )

    patch_metadata = Column(
        JSON,
        nullable=True,
        comment="Additional metadata"
    )

    notes = Column(
        Text,
        nullable=True,
        comment="Additional notes"
    )

    # ========================================================================
    # Relationships
    # ========================================================================
    vulnerability = relationship("Vulnerability", back_populates="patches")
    deployments = relationship("Deployment", back_populates="patch", cascade="all, delete-orphan")

    # ========================================================================
    # Table Constraints
    # ========================================================================
    __table_args__ = (
        # Composite indexes for common queries
        Index("ix_patch_vuln_status", "vulnerability_id", "status"),
        Index("ix_patch_type_status", "patch_type", "status"),
        Index("ix_patch_confidence_status", "confidence_score", "status"),
        Index("ix_patch_test_status", "test_status", "status"),

        # Check constraints
        CheckConstraint("confidence_score >= 0.0 AND confidence_score <= 100.0", name="check_patch_confidence_range"),
        CheckConstraint("version >= 1", name="check_patch_version_positive"),
        CheckConstraint("deployment_count >= 0", name="check_deployment_count_non_negative"),
        CheckConstraint("success_count >= 0", name="check_success_count_non_negative"),
        CheckConstraint("failure_count >= 0", name="check_failure_count_non_negative"),

        {"comment": "Stores AI-generated patches for vulnerability remediation"}
    )

    def __repr__(self) -> str:
        """String representation"""
        return f"<Patch(id={self.id}, vulnerability_id={self.vulnerability_id}, status={self.status}, confidence={self.confidence_score})>"

    @property
    def is_approved(self) -> bool:
        """Check if patch is approved"""
        return self.status == PatchStatus.APPROVED

    @property
    def is_deployed(self) -> bool:
        """Check if patch has been deployed"""
        return self.status == PatchStatus.DEPLOYED

    @property
    def is_high_confidence(self) -> bool:
        """Check if patch has high confidence (>= 80)"""
        return self.confidence_score >= 80

    @property
    def test_passed(self) -> bool:
        """Check if patch passed testing"""
        return self.status == PatchStatus.TEST_PASSED

    @property
    def test_failed(self) -> bool:
        """Check if patch failed testing"""
        return self.status == PatchStatus.TEST_FAILED

    @property
    def success_rate(self) -> float:
        """Calculate deployment success rate"""
        if self.deployment_count == 0:
            return 0.0
        return (self.success_count / self.deployment_count) * 100

    @property
    def age_hours(self) -> float:
        """Calculate age of patch in hours"""
        if self.created_at:
            return (datetime.utcnow() - self.created_at).total_seconds() / 3600
        return 0.0
